const validPinyin = {
  a: ["ā", "á", "ǎ", "à", "a"],
  ai: ["āi", "ái", "ǎi", "ài"],
  an: ["ān", "án", "ǎn", "àn"],
  ang: ["āng", "áng", "ǎng", "àng"],
  ao: ["āo", "áo", "ǎo", "ào"],
  ba: ["bā", "bá", "bǎ", "bà", "ba"],
  bai: ["bāi", "bái", "bǎi", "bài"],
  ban: ["bān", "bǎn", "bàn"],
  bang: ["bāng", "bǎng", "bàng"],
  bao: ["bāo", "báo", "bǎo", "bào"],
  bei: ["bēi", "běi", "bèi"],
  ben: ["běn", "bèn"],
  beng: ["bēng", "béng", "běng", "bèng"],
  bi: ["bī", "bí", "bǐ", "bì"],
  bian: ["biān", "biǎn", "biàn"],
  biao: ["biāo", "biǎo", "biào"],
  bie: ["biē", "bié", "biě"],
  bin: ["bīn", "bìn"],
  bing: ["bīng", "bǐng", "bìng"],
  bo: ["bō", "bó", "bǒ", "bò", "bo"],
  bu: ["bū", "bú", "bǔ", "bù"],
  ca: ["cā", "cǎ", "cà"],
  cai: ["cāi", "cái", "cǎi", "cài"],
  can: ["cān", "cán", "cǎn", "càn"],
  cang: ["cāng", "cáng"],
  cao: ["cāo", "cáo", "cǎo"],
  ce: ["cè"],
  cen: ["cēn", "cén"],
  ceng: ["céng"],
  cha: ["chā", "chá", "chǎ", "chà"],
  chai: ["chāi", "chái", "chài"],
  chan: ["chān", "chán", "chǎn", "chàn"],
  chang: ["chāng", "cháng", "chǎng", "chàng"],
  chao: ["chāo", "cháo", "chǎo", "chào"],
  che: ["chē", "chě", "chè"],
  chen: ["chén", "chěn", "chèn"],
  cheng: ["chēng", "chéng", "chěng", "chèng"],
  chi: ["chī", "chí", "chǐ", "chì"],
  chong: ["chōng", "chóng", "chǒng"],
  chou: ["chōu", "chóu", "chǒu", "chòu"],
  chu: ["chū", "chú", "chǔ", "chù", "chu"],
  chuai: ["chuāi", "chuái", "chuài"],
  chuan: ["chuān", "chuán", "chuǎn", "chuàn"],
  chuang: ["chuāng", "chuáng", "chuǎng", "chuàng"],
  chui: ["chuī", "chuí"],
  chun: ["chūn", "chǔn"],
  chuo: ["chuō", "chuò"],
  ci: ["cī", "cí", "cǐ", "cì"],
  cong: ["cōng", "cóng"],
  cou: ["còu"],
  cu: ["cū", "cù"],
  cuan: ["cuān", "cuàn"],
  cui: ["cuī", "cuǐ", "cuì"],
  cun: ["cūn", "cún", "cǔn"],
  cuo: ["cuō", "cuó", "cuǒ", "cuò"],
  da: ["dā", "dá", "dǎ", "dà", "da"],
  dai: ["dāi", "dǎi", "dài"],
  dan: ["dān", "dǎn", "dàn"],
  dang: ["dāng", "dǎng", "dàng"],
  dao: ["dāo", "dáo", "dǎo", "dào"],
  de: ["dé", "de"],
  dei: ["děi"],
  deng: ["dēng", "děng", "dèng"],
  di: ["dī", "dí", "dǐ", "dì"],
  dian: ["diān", "diǎn", "diàn"],
  diao: ["diāo", "diào"],
  die: ["diē", "dié", "diě"],
  ding: ["dīng", "dǐng", "dìng"],
  diu: ["diū"],
  dong: ["dōng", "dǒng", "dòng"],
  dou: ["dōu", "dǒu", "dòu"],
  du: ["dū", "dú", "dǔ", "dù"],
  duan: ["duān", "duǎn", "duàn"],
  dui: ["duī", "duì"],
  dun: ["dūn", "dǔn", "dùn"],
  duo: ["duō", "duó", "duǒ", "duò", "duo"],
  e: ["ē", "é", "ě", "è"],
  ei: [],
  en: ["ēn", "en"],
  er: ["ér", "ěr", "èr"],
  fa: ["fā", "fá", "fǎ"],
  fan: ["fān", "fán", "fǎn", "fàn"],
  fang: ["fāng", "fáng", "fǎng", "fàng"],
  fei: ["fēi", "féi", "fěi", "fèi"],
  fen: ["fēn", "fén", "fěn", "fèn"],
  feng: ["fēng", "féng", "fěng", "fèng"],
  fo: ["fó"],
  fou: ["fǒu"],
  fu: ["fū", "fú", "fǔ", "fù"],
  ga: ["gā", "gá", "gǎ", "gà"],
  gai: ["gāi", "gǎi", "gài"],
  gan: ["gān", "gǎn", "gàn"],
  gang: ["gāng", "gǎng", "gàng"],
  gao: ["gāo", "gǎo", "gào"],
  ge: ["gē", "gé", "gě", "gè", "ge"],
  gei: ["gěi"],
  gen: ["gēn", "gěn"],
  geng: ["gēng", "gěng", "gèng"],
  gong: ["gōng", "gǒng", "gòng"],
  gou: ["gōu", "gǒu", "gòu"],
  gu: ["gū", "gú", "gǔ", "gù"],
  gua: ["guā", "guǎ", "guà"],
  guai: ["guāi", "guǎi"],
  guan: ["guān", "guǎn", "guàn"],
  guang: ["guāng", "guǎng"],
  gui: ["guī", "guǐ", "guì"],
  gun: ["gǔn", "gùn"],
  guo: ["guō", "guó", "guǒ", "guò"],
  ha: ["hā", "há"],
  hai: ["hái", "hǎi", "hài"],
  han: ["hān", "hán", "hǎn", "hàn"],
  hang: ["háng", "hàng"],
  hao: ["hāo", "háo", "hǎo", "hào"],
  he: ["hē", "hé", "hè"],
  hei: ["hēi"],
  hen: ["hén", "hěn", "hèn"],
  heng: ["hēng", "héng"],
  hong: ["hōng", "hóng", "hǒng"],
  hou: ["hóu", "hǒu", "hòu"],
  hu: ["hū", "hú", "hǔ", "hù"],
  hua: ["huā", "huá", "huà"],
  huai: ["huái", "huài"],
  huan: ["huān", "huán", "huǎn", "huàn"],
  huang: ["huāng", "huáng", "huǎng", "huàng"],
  hui: ["huī", "huí", "huǐ", "huì"],
  hun: ["hūn", "hún", "hùn"],
  huo: ["huō", "huó", "huǒ", "huò"],
  ji: ["jī", "jí", "jǐ", "jì"],
  jia: ["jiā", "jiá", "jiǎ", "jià"],
  jian: ["jiān", "jiǎn", "jiàn"],
  jiang: ["jiāng", "jiǎng", "jiàng"],
  jiao: ["jiāo", "jiáo", "jiǎo", "jiào"],
  jie: ["jiē", "jié", "jiě", "jiè"],
  jin: ["jīn", "jǐn", "jìn"],
  jing: ["jīng", "jǐng", "jìng"],
  jiong: ["jiōng", "jiǒng"],
  jiu: ["jiū", "jiǔ", "jiù"],
  ju: ["jū", "jú", "jǔ", "jù"],
  juan: ["juān", "juǎn", "juàn"],
  jue: ["juē", "jué", "juě", "juè"],
  jun: ["jūn", "jùn"],
  ka: ["kā", "kǎ"],
  kai: ["kāi", "kǎi"],
  kan: ["kān", "kǎn", "kàn"],
  kang: ["kāng", "kàng"],
  kao: ["kāo", "kǎo", "kào"],
  ke: ["kē", "ké", "kě", "kè"],
  ken: ["kěn", "kèn"],
  keng: ["kēng"],
  kong: ["kōng", "kǒng", "kòng"],
  kou: ["kōu", "kǒu", "kòu"],
  ku: ["kū", "kǔ", "kù"],
  kua: ["kuā", "kuǎ", "kuà"],
  kuai: ["kuài"],
  kuan: ["kuān", "kuǎn"],
  kuang: ["kuāng", "kuáng", "kuàng"],
  kui: ["kuī", "kuí", "kuì"],
  kun: ["kūn", "kǔn", "kùn"],
  kuo: ["kuò"],
  la: ["lā", "lá", "lǎ", "là", "la"],
  lai: ["lái", "lài"],
  lan: ["lán", "lǎn", "làn"],
  lang: ["láng", "lǎng", "làng"],
  lao: ["lāo", "láo", "lǎo", "lào"],
  le: ["lè", "le"],
  lei: ["lēi", "léi", "lěi", "lèi"],
  leng: ["léng", "lěng", "lèng"],
  li: ["lī", "lí", "lǐ", "lì", "li"],
  lia: ["liǎ"],
  lian: ["lián", "liǎn", "liàn"],
  liang: ["liáng", "liǎng", "liàng"],
  liao: ["liāo", "liáo", "liǎo", "liào"],
  lie: ["liē", "liè"],
  lin: ["lín", "lín", "lǐn", "lìn"],
  ling: ["líng", "lǐng", "lìng"],
  liu: ["liū", "liú", "liǔ", "liù"],
  long: ["lóng", "lǒng"],
  lou: ["lóu", "lǒu", "lòu"],
  lu: ["lū", "lú", "lǔ", "lù"],
  luan: ["luán", "luǎn", "luàn"],
  lun: ["lún", "lùn"],
  luo: ["luō", "luó", "luǒ", "luò", "luo"],
  lv: ["lǘ", "lǚ", "lǜ"],
  lve: ["lüè"],
  m: ["m"],
  ma: ["mā", "má", "mǎ", "mà", "ma"],
  mai: ["mái", "mǎi", "mài"],
  man: ["mán", "mǎn", "màn"],
  mang: ["máng", "mǎng"],
  mao: ["māo", "máo", "mǎo", "mào"],
  me: ["me"],
  mei: ["méi", "měi", "mèi"],
  men: ["mén", "men"],
  meng: ["méng", "měng", "mèng"],
  mi: ["mī", "mí", "mǐ", "mì"],
  mian: ["mián", "miǎn", "miàn"],
  miao: ["miáo", "miǎo", "miào"],
  mie: ["miē", "miè"],
  min: ["mín", "mǐn"],
  ming: ["míng", "mìng"],
  miu: ["miù"],
  mo: ["mō", "mó", "mǒ", "mò"],
  mou: ["móu", "mǒu"],
  mu: ["mú", "mǔ", "mù"],
  na: ["nā", "ná", "nǎ", "nà", "na"],
  nai: ["nǎi", "nài"],
  nan: ["nán", "nǎn", "nàn"],
  nang: ["náng"],
  nao: ["náo", "nǎo", "nào"],
  ne: ["ne"],
  nei: ["nèi"],
  nen: ["nèn"],
  neng: ["néng"],
  ni: ["nī", "ní", "nǐ", "nì"],
  nian: ["nián", "niǎn", "niàn"],
  niang: ["niáng"],
  niao: ["niǎo", "niào"],
  nie: ["niē", "niè"],
  nin: ["nín"],
  ning: ["níng", "nìng"],
  niu: ["niú", "niǔ", "niù"],
  nong: ["nóng", "nòng"],
  nou: [],
  nu: ["nú", "nǔ", "nù"],
  nuan: ["nuǎn"],
  nun: [],
  nuo: ["nuó", "nuò"],
  nv: ["nǚ"],
  nve: ["nüè"],
  o: ["ó", "ǒ", "ò", "o"],
  ou: ["ōu", "ǒu"],
  pa: ["pā", "pá", "pà"],
  pai: ["pāi", "pái", "pài"],
  pan: ["pān", "pán", "pàn"],
  pang: ["páng", "pàng"],
  pao: ["pāo", "páo", "pǎo", "pào"],
  pei: ["péi", "pěi", "pèi"],
  pen: ["pēn", "pén"],
  peng: ["pēng", "péng", "pěng", "pèng"],
  pi: ["pī", "pí", "pǐ", "pì"],
  pian: ["piān", "pián", "piàn"],
  piao: ["piāo", "piáo", "piǎo", "piào"],
  pie: ["piē", "piě"],
  pin: ["pīn", "pín", "pǐn"],
  ping: ["píng", "pǐng"],
  po: ["pō", "pó", "pǒ", "pò"],
  pou: ["pōu", "pǒu"],
  pu: ["pū", "pú", "pǔ", "pù"],
  qi: ["qī", "qí", "qǐ", "qì"],
  qia: ["qiā", "qiǎ"],
  qian: ["qiān", "qián", "qiǎn", "qiàn"],
  qiang: ["qiāng", "qiáng", "qiǎng", "qiàng"],
  qiao: ["qiāo", "qiáo", "qiǎo", "qiào"],
  qie: ["qiē", "qiè"],
  qin: ["qīn", "qín", "qǐn"],
  qing: ["qīng", "qíng", "qǐng", "qìng"],
  qiong: ["qióng"],
  qiu: ["qiū", "qiú"],
  qu: ["qū", "qú", "qǔ", "qù"],
  quan: ["quān", "quán", "quàn"],
  que: ["quē", "què"],
  qun: ["qún"],
  ran: ["rán", "rǎn"],
  rang: ["rāng", "ráng", "rǎng", "ràng"],
  rao: ["ráo", "rǎo"],
  re: ["rě", "rè"],
  ren: ["rén", "rěn", "rèn"],
  reng: ["rēng", "réng"],
  ri: ["rì"],
  rong: ["róng", "rǒng"],
  rou: ["róu", "ròu"],
  ru: ["rú", "rǔ", "rù"],
  ruan: ["ruǎn"],
  rui: ["ruí", "ruǐ", "ruì"],
  run: ["rùn"],
  ruo: ["ruò"],
  sa: ["sā", "sǎ", "sà"],
  sai: ["sāi", "sài"],
  san: ["sān", "sǎn", "sàn"],
  sang: ["sāng", "sǎng", "sàng"],
  sao: ["sāo", "sǎo", "sào"],
  se: ["sè"],
  sen: ["sēn"],
  seng: ["sēng"],
  sha: ["shā", "shá", "shǎ", "shà"],
  shai: ["shǎi", "shài"],
  shan: ["shān", "shǎn", "shàn"],
  shang: ["shāng", "shǎng", "shàng"],
  shao: ["shāo", "sháo", "shǎo", "shào"],
  she: ["shē", "shé", "shě", "shè"],
  shei: ["shéi"],
  shen: ["shēn", "shén", "shěn", "shèn"],
  sheng: ["shēng", "shéng", "shěng", "shèng"],
  shi: ["shī", "shí", "shǐ", "shì"],
  shou: ["shōu", "shǒu", "shòu"],
  shu: ["shū", "shú", "shǔ", "shù"],
  shua: ["shuā", "shuǎ", "shuà"],
  shuai: ["shuāi", "shuǎi", "shuài"],
  shuan: ["shuān", "shuàn"],
  shuang: ["shuāng"],
  shui: ["shuí", "shuǐ"],
  shun: ["shǔn", "shùn"],
  shuo: ["shuō", "shuò"],
  si: ["sī", "sǐ", "sì"],
  song: ["sōng", "sǒng", "sòng"],
  sou: ["sōu", "sǒu"],
  su: ["sū", "sú", "sù"],
  suan: ["suān", "suàn"],
  sui: ["suī", "suí", "suǐ", "suì"],
  sun: ["sūn", "sǔn"],
  suo: ["suō", "suǒ"],
  ta: ["tā", "tǎ", "tà"],
  tai: ["tāi", "tài"],
  tan: ["tān", "tán", "tǎn", "tàn"],
  tang: ["tāng", "táng", "tǎng", "tàng"],
  tao: ["tāo", "táo", "tǎo", "tào"],
  te: ["tè"],
  teng: ["téng"],
  ti: ["tī", "tí", "tǐ", "tì"],
  tian: ["tiān", "tián", "tiǎn"],
  tiao: ["tiāo", "tiáo", "tiǎo"],
  tie: ["tiē", "tiě", "tiè"],
  ting: ["tīng", "tíng", "tǐng"],
  tong: ["tōng", "tóng", "tǒng", "tòng"],
  tou: ["tōu", "tóu", "tòu"],
  tu: ["tū", "tú", "tǔ", "tù"],
  tuan: ["tuán"],
  tui: ["tuī", "tuí", "tuì"],
  tun: ["tūn", "tún"],
  tuo: ["tuō", "tuó", "tuǒ", "tuò"],
  wa: ["wā", "wá", "wǎ", "wà"],
  wai: ["wāi", "wài"],
  wan: ["wān", "wán", "wǎn", "wàn"],
  wang: ["wāng", "wáng", "wǎng", "wàng"],
  wei: ["wēi", "wéi", "wěi", "wèi"],
  wen: ["wēn", "wén", "wěn", "wèn"],
  weng: ["wēng", "wěng"],
  wo: ["wō", "wǒ", "wò"],
  wu: ["wū", "wú", "wǔ", "wù"],
  xi: ["xī", "xí", "xǐ", "xì"],
  xia: ["xiā", "xiá", "xià"],
  xian: ["xiān", "xián", "xiǎn", "xiàn"],
  xiang: ["xiāng", "xiáng", "xiǎng", "xiàng"],
  xiao: ["xiāo", "xiáo", "xiǎo", "xiào"],
  xie: ["xiē", "xié", "xiě", "xiè"],
  xin: ["xīn", "xìn"],
  xing: ["xīng", "xíng", "xǐng", "xìng"],
  xiong: ["xiōng", "xiōng"],
  xiu: ["xiū", "xiǔ", "xiù"],
  xu: ["xū", "xú", "xǔ", "xù"],
  xuan: ["xuān", "xuán", "xuǎn", "xuàn"],
  xue: ["xuē", "xué", "xuě"],
  xun: ["xūn", "xún", "xùn"],
  ya: ["yā", "yá", "yǎ", "yà"],
  yan: ["yān", "yán", "yǎn", "yàn"],
  yang: ["yāng", "yáng", "yǎng", "yàng"],
  yao: ["yāo", "yáo", "yǎo", "yào"],
  ye: ["yē", "yé", "yě", "yè"],
  yi: ["yī", "yí", "yǐ", "yì"],
  yin: ["yīn", "yín", "yǐn", "yìn"],
  ying: ["yīng", "yíng", "yǐng", "yìng"],
  yo: ["yo"],
  yong: ["yōng", "yǒng", "yòng"],
  you: ["yōu", "yóu", "yǒu", "yòu"],
  yu: ["yū", "yú", "yǔ", "yù"],
  yuan: ["yuān", "yuán", "yuǎn", "yuàn"],
  yue: ["yuē", "yuè"],
  yun: ["yūn", "yún", "yǔn", "yùn"],
  za: ["zā", "zá", "zǎ"],
  zai: ["zāi", "zǎi", "zài"],
  zan: ["zān", "zǎn", "zàn"],
  zang: ["zāng", "zàng"],
  zao: ["zāo", "záo", "zǎo", "zào"],
  ze: ["zé", "zéi", "zè"],
  zei: ["zéi"],
  zen: ["zěn"],
  zeng: ["zēng", "zèng"],
  zha: ["zhā", "zhá", "zhǎ", "zhà"],
  zhai: ["zhāi", "zhái", "zhǎi", "zhài"],
  zhan: ["zhān", "zhǎn", "zhàn"],
  zhang: ["zhāng", "zhǎng", "zhàng"],
  zhao: ["zhāo", "zhǎo", "zhào"],
  zhe: ["zhē", "zhé", "zhě", "zhè", "zhe"],
  zhen: ["zhēn", "zhěn", "zhèn"],
  zheng: ["zhēng", "zhěng", "zhèng"],
  zhi: ["zhī", "zhí", "zhǐ", "zhì"],
  zhong: ["zhōng", "zhǒng", "zhòng"],
  zhou: ["zhōu", "zhóu", "zhǒu", "zhòu"],
  zhu: ["zhū", "zhú", "zhǔ", "zhù"],
  zhua: ["zhuā"],
  zhuai: ["zhuǎi"],
  zhuan: ["zhuān", "zhuǎn", "zhuàn"],
  zhuang: ["zhuāng", "zhuàng"],
  zhui: ["zhuī", "zhuì"],
  zhun: ["zhǔn"],
  zhuo: ["zhuō", "zhuó"],
  zi: ["zī", "zǐ", "zì"],
  zong: ["zōng", "zǒng", "zòng"],
  zou: ["zǒu", "zòu"],
  zu: ["zū", "zú", "zǔ"],
  zuan: ["zuān", "zuǎn"],
  zui: ["zuǐ", "zuì"],
  zun: ["zūn"],
  zuo: ["zuō", "zuó", "zuǒ", "zuò"],
};
