const validPinyin = {
  a: [
    { pinyin: "ā", char: "啊" },
    { pinyin: "á", char: "啊" },
    { pinyin: "à", char: "啊" },
    { pinyin: "a", char: "啊" },
  ],
  ai: [
    { pinyin: "āi", char: "哀" },
    { pinyin: "ái", char: "挨" },
    { pinyin: "ǎi", char: "矮" },
    { pinyin: "ài", char: "爱" },
  ],
  an: [
    { pinyin: "ān", char: "安" },
    { pinyin: "ǎn", char: "俺" },
    { pinyin: "àn", char: "案" },
  ],
  ang: [
    { pinyin: "āng", char: "肮" },
    { pinyin: "áng", char: "昂" },
    { pinyin: "àng", char: "盎" },
  ],
  ao: [
    { pinyin: "āo", char: "凹" },
    { pinyin: "áo", char: "熬" },
    { pinyin: "ǎo", char: "袄" },
    { pinyin: "ào", char: "傲" },
  ],
  ba: [
    { pinyin: "bā", char: "八" },
    { pinyin: "bá", char: "拔" },
    { pinyin: "bǎ", char: "把" },
    { pinyin: "bà", char: "爸" },
    { pinyin: "ba", char: "吧" },
  ],
  bai: [
    { pinyin: "bāi", char: "掰" },
    { pinyin: "bái", char: "白" },
    { pinyin: "bǎi", char: "百" },
    { pinyin: "bài", char: "败" },
  ],
  ban: [
    { pinyin: "bān", char: "班" },
    { pinyin: "bǎn", char: "板" },
    { pinyin: "bàn", char: "半" },
  ],
  bang: [
    { pinyin: "bāng", char: "帮" },
    { pinyin: "bǎng", char: "榜" },
    { pinyin: "bàng", char: "棒" },
  ],
  bao: [
    { pinyin: "bāo", char: "包" },
    { pinyin: "báo", char: "薄" },
    { pinyin: "bǎo", char: "宝" },
    { pinyin: "bào", char: "抱" },
  ],
  bei: [
    { pinyin: "bēi", char: "杯" },
    { pinyin: "běi", char: "北" },
    { pinyin: "bèi", char: "被" },
  ],
  ben: [
    { pinyin: "běn", char: "本" },
    { pinyin: "bèn", char: "笨" },
  ],
  beng: [
    { pinyin: "bēng", char: "崩" },
    { pinyin: "béng", char: "甭" },
    { pinyin: "běng", char: "绷" },
    { pinyin: "bèng", char: "泵" },
  ],
  bi: [
    { pinyin: "bī", char: "逼" },
    { pinyin: "bí", char: "鼻" },
    { pinyin: "bǐ", char: "笔" },
    { pinyin: "bì", char: "必" },
  ],
  bian: [
    { pinyin: "biān", char: "边" },
    { pinyin: "biǎn", char: "贬" },
    { pinyin: "biàn", char: "变" },
  ],
  biao: [
    { pinyin: "biāo", char: "标" },
    { pinyin: "biǎo", char: "表" },
    { pinyin: "biào", char: "婊" },
  ],
  bie: [
    { pinyin: "biē", char: "憋" },
    { pinyin: "bié", char: "别" },
    { pinyin: "biě", char: "瘪" },
  ],
  bin: [
    { pinyin: "bīn", char: "宾" },
    { pinyin: "bìn", char: "鬓" },
  ],
  bing: [
    { pinyin: "bīng", char: "兵" },
    { pinyin: "bǐng", char: "丙" },
    { pinyin: "bìng", char: "病" },
  ],
  bo: [
    { pinyin: "bō", char: "波" },
    { pinyin: "bó", char: "伯" },
    { pinyin: "bǒ", char: "簸" },
    { pinyin: "bò", char: "薄" },
    { pinyin: "bo", char: "卜" },
  ],
  bu: [
    { pinyin: "bū", char: "逋" },
    { pinyin: "bú", char: "不" },
    { pinyin: "bǔ", char: "补" },
    { pinyin: "bù", char: "部" },
  ],
  ca: [
    { pinyin: "cā", char: "擦" },
    { pinyin: "cǎ", char: "嚓" },
    { pinyin: "cà", char: "蹅" },
  ],
  cai: [
    { pinyin: "cāi", char: "猜" },
    { pinyin: "cái", char: "才" },
    { pinyin: "cǎi", char: "彩" },
    { pinyin: "cài", char: "菜" },
  ],
  can: [
    { pinyin: "cān", char: "餐" },
    { pinyin: "cán", char: "残" },
    { pinyin: "cǎn", char: "惨" },
    { pinyin: "càn", char: "灿" },
  ],
  cang: [
    { pinyin: "cāng", char: "苍" },
    { pinyin: "cáng", char: "藏" },
  ],
  cao: [
    { pinyin: "cāo", char: "操" },
    { pinyin: "cáo", char: "曹" },
    { pinyin: "cǎo", char: "草" },
  ],
  ce: [{ pinyin: "cè", char: "册" }],
  cen: [
    { pinyin: "cēn", char: "参" },
    { pinyin: "cén", char: "岑" },
  ],
  ceng: [{ pinyin: "céng", char: "层" }],
  cha: [
    { pinyin: "chā", char: "插" },
    { pinyin: "chá", char: "茶" },
    { pinyin: "chǎ", char: "衩" },
    { pinyin: "chà", char: "差" },
  ],
  chai: [
    { pinyin: "chāi", char: "拆" },
    { pinyin: "chái", char: "柴" },
    { pinyin: "chài", char: "虿" },
  ],
  chan: [
    { pinyin: "chān", char: "搀" },
    { pinyin: "chán", char: "禅" },
    { pinyin: "chǎn", char: "产" },
    { pinyin: "chàn", char: "颤" },
  ],
  chang: [
    { pinyin: "chāng", char: "昌" },
    { pinyin: "cháng", char: "长" },
    { pinyin: "chǎng", char: "厂" },
    { pinyin: "chàng", char: "唱" },
  ],
  chao: [
    { pinyin: "chāo", char: "超" },
    { pinyin: "cháo", char: "朝" },
    { pinyin: "chǎo", char: "吵" },
    { pinyin: "chào", char: "耖" },
  ],
  che: [
    { pinyin: "chē", char: "车" },
    { pinyin: "chě", char: "扯" },
    { pinyin: "chè", char: "撤" },
  ],
  chen: [
    { pinyin: "chén", char: "沉" },
    { pinyin: "chěn", char: "诊" },
    { pinyin: "chèn", char: "称" },
  ],
  cheng: [
    { pinyin: "chēng", char: "称" },
    { pinyin: "chéng", char: "成" },
    { pinyin: "chěng", char: "逞" },
    { pinyin: "chèng", char: "秤" },
  ],
  chi: [
    { pinyin: "chī", char: "吃" },
    { pinyin: "chí", char: "持" },
    { pinyin: "chǐ", char: "尺" },
    { pinyin: "chì", char: "赤" },
  ],
  chong: [
    { pinyin: "chōng", char: "充" },
    { pinyin: "chóng", char: "虫" },
    { pinyin: "chǒng", char: "宠" },
  ],
  chou: [
    { pinyin: "chōu", char: "抽" },
    { pinyin: "chóu", char: "愁" },
    { pinyin: "chǒu", char: "丑" },
    { pinyin: "chòu", char: "臭" },
  ],
  chu: [
    { pinyin: "chū", char: "出" },
    { pinyin: "chú", char: "除" },
    { pinyin: "chǔ", char: "楚" },
    { pinyin: "chù", char: "处" },
    { pinyin: "chu", char: "褚" },
  ],
  chuai: [
    { pinyin: "chuāi", char: "揣" },
    { pinyin: "chuái", char: "踹" },
    { pinyin: "chuài", char: "啜" },
  ],
  chuan: [
    { pinyin: "chuān", char: "川" },
    { pinyin: "chuán", char: "船" },
    { pinyin: "chuǎn", char: "喘" },
    { pinyin: "chuàn", char: "串" },
  ],
  chuang: [
    { pinyin: "chuāng", char: "窗" },
    { pinyin: "chuáng", char: "床" },
    { pinyin: "chuǎng", char: "闯" },
    { pinyin: "chuàng", char: "创" },
  ],
  chui: [
    { pinyin: "chuī", char: "吹" },
    { pinyin: "chuí", char: "垂" },
  ],
  chun: [
    { pinyin: "chūn", char: "春" },
    { pinyin: "chǔn", char: "蠢" },
  ],
  chuo: [
    { pinyin: "chuō", char: "戳" },
    { pinyin: "chuò", char: "啜" },
  ],
  ci: [
    { pinyin: "cī", char: "呲" },
    { pinyin: "cí", char: "词" },
    { pinyin: "cǐ", char: "此" },
    { pinyin: "cì", char: "次" },
  ],
  cong: [
    { pinyin: "cōng", char: "聪" },
    { pinyin: "cóng", char: "从" },
  ],
  cou: [{ pinyin: "còu", char: "凑" }],
  cu: [
    { pinyin: "cū", char: "粗" },
    { pinyin: "cù", char: "促" },
  ],
  cuan: [
    { pinyin: "cuān", char: "蹿" },
    { pinyin: "cuàn", char: "窜" },
  ],
  cui: [
    { pinyin: "cuī", char: "催" },
    { pinyin: "cuǐ", char: "璀" },
    { pinyin: "cuì", char: "脆" },
  ],
  cun: [
    { pinyin: "cūn", char: "村" },
    { pinyin: "cún", char: "存" },
    { pinyin: "cǔn", char: "忖" },
  ],
  cuo: [
    { pinyin: "cuō", char: "搓" },
    { pinyin: "cuó", char: "嵯" },
    { pinyin: "cuǒ", char: "脞" },
    { pinyin: "cuò", char: "错" },
  ],
  da: [
    { pinyin: "dā", char: "搭" },
    { pinyin: "dá", char: "答" },
    { pinyin: "dǎ", char: "打" },
    { pinyin: "dà", char: "大" },
    { pinyin: "da", char: "答" },
  ],
  dai: [
    { pinyin: "dāi", char: "呆" },
    { pinyin: "dǎi", char: "逮" },
    { pinyin: "dài", char: "带" },
  ],
  dan: [
    { pinyin: "dān", char: "单" },
    { pinyin: "dǎn", char: "胆" },
    { pinyin: "dàn", char: "但" },
  ],
  dang: [
    { pinyin: "dāng", char: "当" },
    { pinyin: "dǎng", char: "党" },
    { pinyin: "dàng", char: "荡" },
  ],
  dao: [
    { pinyin: "dāo", char: "刀" },
    { pinyin: "dáo", char: "叨" },
    { pinyin: "dǎo", char: "岛" },
    { pinyin: "dào", char: "到" },
  ],
  de: [
    { pinyin: "dé", char: "得" },
    { pinyin: "de", char: "的" },
  ],
  dei: [{ pinyin: "děi", char: "得" }],
  deng: [
    { pinyin: "dēng", char: "灯" },
    { pinyin: "děng", char: "等" },
    { pinyin: "dèng", char: "瞪" },
  ],
  di: [
    { pinyin: "dī", char: "低" },
    { pinyin: "dí", char: "敌" },
    { pinyin: "dǐ", char: "底" },
    { pinyin: "dì", char: "地" },
  ],
  dian: [
    { pinyin: "diān", char: "颠" },
    { pinyin: "diǎn", char: "点" },
    { pinyin: "diàn", char: "电" },
  ],
  diao: [
    { pinyin: "diāo", char: "刁" },
    { pinyin: "diào", char: "掉" },
  ],
  die: [
    { pinyin: "diē", char: "爹" },
    { pinyin: "dié", char: "蝶" },
    { pinyin: "diě", char: "碟" },
  ],
  ding: [
    { pinyin: "dīng", char: "丁" },
    { pinyin: "dǐng", char: "顶" },
    { pinyin: "dìng", char: "定" },
  ],
  diu: [{ pinyin: "diū", char: "丢" }],
  dong: [
    { pinyin: "dōng", char: "东" },
    { pinyin: "dǒng", char: "懂" },
    { pinyin: "dòng", char: "动" },
  ],
  dou: [
    { pinyin: "dōu", char: "都" },
    { pinyin: "dǒu", char: "抖" },
    { pinyin: "dòu", char: "豆" },
  ],
  du: [
    { pinyin: "dū", char: "都" },
    { pinyin: "dú", char: "读" },
    { pinyin: "dǔ", char: "堵" },
    { pinyin: "dù", char: "度" },
  ],
  duan: [
    { pinyin: "duān", char: "端" },
    { pinyin: "duǎn", char: "短" },
    { pinyin: "duàn", char: "断" },
  ],
  dui: [
    { pinyin: "duī", char: "堆" },
    { pinyin: "duì", char: "对" },
  ],
  dun: [
    { pinyin: "dūn", char: "吨" },
    { pinyin: "dǔn", char: "盹" },
    { pinyin: "dùn", char: "顿" },
  ],
  duo: [
    { pinyin: "duō", char: "多" },
    { pinyin: "duó", char: "夺" },
    { pinyin: "duǒ", char: "躲" },
    { pinyin: "duò", char: "舵" },
    { pinyin: "duo", char: "哆" },
  ],
  e: [
    { pinyin: "ē", char: "阿" },
    { pinyin: "é", char: "俄" },
    { pinyin: "ě", char: "恶" },
    { pinyin: "è", char: "饿" },
  ],
  ei: [],
  en: [
    { pinyin: "ēn", char: "恩" },
    { pinyin: "en", char: "嗯" },
  ],
  er: [
    { pinyin: "ér", char: "而" },
    { pinyin: "ěr", char: "耳" },
    { pinyin: "èr", char: "二" },
  ],
  fa: [
    { pinyin: "fā", char: "发" },
    { pinyin: "fá", char: "罚" },
    { pinyin: "fǎ", char: "法" },
  ],
  fan: [
    { pinyin: "fān", char: "翻" },
    { pinyin: "fán", char: "凡" },
    { pinyin: "fǎn", char: "反" },
    { pinyin: "fàn", char: "饭" },
  ],
  fang: [
    { pinyin: "fāng", char: "方" },
    { pinyin: "fáng", char: "房" },
    { pinyin: "fǎng", char: "访" },
    { pinyin: "fàng", char: "放" },
  ],
  fei: [
    { pinyin: "fēi", char: "非" },
    { pinyin: "féi", char: "肥" },
    { pinyin: "fěi", char: "匪" },
    { pinyin: "fèi", char: "费" },
  ],
  fo: [{ pinyin: "fó", char: "佛" }],
  fou: [{ pinyin: "fǒu", char: "否" }],
  fu: [
    { pinyin: "fū", char: "夫" },
    { pinyin: "fú", char: "福" },
    { pinyin: "fǔ", char: "府" },
    { pinyin: "fù", char: "副" },
  ],
  ga: [
    { pinyin: "gā", char: "嘎" },
    { pinyin: "gá", char: "伽" },
    { pinyin: "gǎ", char: "gǎ" },
    { pinyin: "gà", char: "尬" },
  ],
  gai: [
    { pinyin: "gāi", char: "该" },
    { pinyin: "gǎi", char: "改" },
    { pinyin: "gài", char: "盖" },
  ],
  gan: [
    { pinyin: "gān", char: "干" },
    { pinyin: "gǎn", char: "敢" },
    { pinyin: "gàn", char: "干" },
  ],
  gang: [
    { pinyin: "gāng", char: "钢" },
    { pinyin: "gǎng", char: "港" },
    { pinyin: "gàng", char: "杠" },
  ],
  gao: [
    { pinyin: "gāo", char: "高" },
    { pinyin: "gǎo", char: "搞" },
    { pinyin: "gào", char: "告" },
  ],
  ge: [
    { pinyin: "gē", char: "哥" },
    { pinyin: "gé", char: "格" },
    { pinyin: "gě", char: "葛" },
    { pinyin: "gè", char: "个" },
    { pinyin: "ge", char: "个" },
  ],
  gei: [{ pinyin: "gěi", char: "给" }],
  gen: [
    { pinyin: "gēn", char: "根" },
    { pinyin: "gěn", char: "艮" },
  ],
  geng: [
    { pinyin: "gēng", char: "更" },
    { pinyin: "gěng", char: "耿" },
    { pinyin: "gèng", char: "更" },
  ],
  gong: [
    { pinyin: "gōng", char: "工" },
    { pinyin: "gǒng", char: "拱" },
    { pinyin: "gòng", char: "共" },
  ],
  gou: [
    { pinyin: "gōu", char: "勾" },
    { pinyin: "gǒu", char: "狗" },
    { pinyin: "gòu", char: "够" },
  ],
  gu: [
    { pinyin: "gū", char: "估" },
    { pinyin: "gú", char: "骨" },
    { pinyin: "gǔ", char: "古" },
    { pinyin: "gù", char: "故" },
  ],
  gua: [
    { pinyin: "guā", char: "瓜" },
    { pinyin: "guǎ", char: "寡" },
    { pinyin: "guà", char: "挂" },
  ],
  guai: [
    { pinyin: "guāi", char: "乖" },
    { pinyin: "guǎi", char: "拐" },
  ],
  guan: [
    { pinyin: "guān", char: "关" },
    { pinyin: "guǎn", char: "管" },
    { pinyin: "guàn", char: "惯" },
  ],
  guang: [
    { pinyin: "guāng", char: "光" },
    { pinyin: "guǎng", char: "广" },
  ],
  gui: [
    { pinyin: "guī", char: "归" },
    { pinyin: "guǐ", char: "鬼" },
    { pinyin: "guì", char: "贵" },
  ],
  gun: [
    { pinyin: "gǔn", char: "滚" },
    { pinyin: "gùn", char: "棍" },
  ],
  guo: [
    { pinyin: "guō", char: "锅" },
    { pinyin: "guó", char: "国" },
    { pinyin: "guǒ", char: "果" },
    { pinyin: "guò", char: "过" },
  ],
  ha: [
    { pinyin: "hā", char: "哈" },
    { pinyin: "há", char: "蛤" },
  ],
  hai: [
    { pinyin: "hái", char: "还" },
    { pinyin: "hǎi", char: "海" },
    { pinyin: "hài", char: "害" },
  ],
  han: [
    { pinyin: "hān", char: "酣" },
    { pinyin: "hán", char: "含" },
    { pinyin: "hǎn", char: "喊" },
    { pinyin: "hàn", char: "汉" },
  ],
  hang: [
    { pinyin: "háng", char: "行" },
    { pinyin: "hàng", char: "巷" },
  ],
  hao: [
    { pinyin: "hāo", char: "蒿" },
    { pinyin: "háo", char: "毫" },
    { pinyin: "hǎo", char: "好" },
    { pinyin: "hào", char: "号" },
  ],
  he: [
    { pinyin: "hē", char: "喝" },
    { pinyin: "hé", char: "和" },
    { pinyin: "hè", char: "贺" },
  ],
  hei: [{ pinyin: "hēi", char: "黑" }],
  hen: [
    { pinyin: "hén", char: "痕" },
    { pinyin: "hěn", char: "很" },
    { pinyin: "hèn", char: "恨" },
  ],
  heng: [
    { pinyin: "hēng", char: "哼" },
    { pinyin: "héng", char: "恒" },
  ],
  hong: [
    { pinyin: "hōng", char: "轰" },
    { pinyin: "hóng", char: "红" },
    { pinyin: "hǒng", char: "哄" },
  ],
  hou: [
    { pinyin: "hóu", char: "喉" },
    { pinyin: "hǒu", char: "吼" },
    { pinyin: "hòu", char: "后" },
  ],
  hu: [
    { pinyin: "hū", char: "乎" },
    { pinyin: "hú", char: "胡" },
    { pinyin: "hǔ", char: "虎" },
    { pinyin: "hù", char: "互" },
  ],
  hua: [
    { pinyin: "huā", char: "花" },
    { pinyin: "huá", char: "华" },
    { pinyin: "huà", char: "画" },
  ],
  huai: [
    { pinyin: "huái", char: "怀" },
    { pinyin: "huài", char: "坏" },
  ],
  huan: [
    { pinyin: "huān", char: "欢" },
    { pinyin: "huán", char: "环" },
    { pinyin: "huǎn", char: "缓" },
    { pinyin: "huàn", char: "换" },
  ],
  huang: [
    { pinyin: "huāng", char: "慌" },
    { pinyin: "huáng", char: "黄" },
    { pinyin: "huǎng", char: "晃" },
    { pinyin: "huàng", char: "晃" },
  ],
  hui: [
    { pinyin: "huī", char: "灰" },
    { pinyin: "huí", char: "回" },
    { pinyin: "huǐ", char: "毁" },
    { pinyin: "huì", char: "会" },
  ],
  hun: [
    { pinyin: "hūn", char: "婚" },
    { pinyin: "hún", char: "魂" },
    { pinyin: "hùn", char: "混" },
  ],
  huo: [
    { pinyin: "huō", char: "豁" },
    { pinyin: "huó", char: "活" },
    { pinyin: "huǒ", char: "火" },
    { pinyin: "huò", char: "或" },
  ],
  ji: [
    { pinyin: "jī", char: "机" },
    { pinyin: "jí", char: "极" },
    { pinyin: "jǐ", char: "几" },
    { pinyin: "jì", char: "计" },
  ],
  jia: [
    { pinyin: "jiā", char: "家" },
    { pinyin: "jiá", char: "夹" },
    { pinyin: "jiǎ", char: "甲" },
    { pinyin: "jià", char: "价" },
  ],
  jian: [
    { pinyin: "jiān", char: "尖" },
    { pinyin: "jiǎn", char: "茧" },
    { pinyin: "jiàn", char: "件" },
  ],
  jiang: [
    { pinyin: "jiāng", char: "江" },
    { pinyin: "jiǎng", char: "讲" },
    { pinyin: "jiàng", char: "匠" },
  ],
  jiao: [
    { pinyin: "jiāo", char: "交" },
    { pinyin: "jiáo", char: "嚼" },
    { pinyin: "jiǎo", char: "角" },
    { pinyin: "jiào", char: "教" },
  ],
  jie: [
    { pinyin: "jiē", char: "接" },
    { pinyin: "jié", char: "节" },
    { pinyin: "jiě", char: "姐" },
    { pinyin: "jiè", char: "借" },
  ],
  jin: [
    { pinyin: "jīn", char: "金" },
    { pinyin: "jǐn", char: "仅" },
    { pinyin: "jìn", char: "进" },
  ],
  jing: [
    { pinyin: "jīng", char: "惊" },
    { pinyin: "jǐng", char: "景" },
    { pinyin: "jìng", char: "静" },
  ],
  jiong: [
    { pinyin: "jiōng", char: "扃" },
    { pinyin: "jiǒng", char: "窘" },
  ],
  jiu: [
    { pinyin: "jiū", char: "纠" },
    { pinyin: "jiǔ", char: "九" },
    { pinyin: "jiù", char: "就" },
  ],
  ju: [
    { pinyin: "jū", char: "居" },
    { pinyin: "jú", char: "局" },
    { pinyin: "jǔ", char: "举" },
    { pinyin: "jù", char: "句" },
  ],
  juan: [
    { pinyin: "juān", char: "捐" },
    { pinyin: "juǎn", char: "卷" },
    { pinyin: "juàn", char: "倦" },
  ],
  jue: [
    { pinyin: "juē", char: "撅" },
    { pinyin: "jué", char: "决" },
    { pinyin: "juě", char: "倔" },
    { pinyin: "juè", char: "爵" },
  ],
  jun: [
    { pinyin: "jūn", char: "军" },
    { pinyin: "jùn", char: "俊" },
  ],
  ka: [
    { pinyin: "kā", char: "咖" },
    { pinyin: "kǎ", char: "卡" },
  ],
  kai: [
    { pinyin: "kāi", char: "开" },
    { pinyin: "kǎi", char: "凯" },
  ],
  kan: [
    { pinyin: "kān", char: "刊" },
    { pinyin: "kǎn", char: "砍" },
    { pinyin: "kàn", char: "看" },
  ],
  kang: [
    { pinyin: "kāng", char: "康" },
    { pinyin: "kàng", char: "抗" },
  ],
  kao: [
    { pinyin: "kāo", char: "掏" },
    { pinyin: "kǎo", char: "考" },
    { pinyin: "kào", char: "靠" },
  ],
  ke: [
    { pinyin: "kē", char: "科" },
    { pinyin: "ké", char: "壳" },
    { pinyin: "kě", char: "可" },
    { pinyin: "kè", char: "客" },
  ],
  ken: [
    { pinyin: "kěn", char: "肯" },
    { pinyin: "kèn", char: "啃" },
  ],
  keng: [{ pinyin: "kēng", char: "坑" }],
  kong: [
    { pinyin: "kōng", char: "空" },
    { pinyin: "kǒng", char: "孔" },
    { pinyin: "kòng", char: "控" },
  ],
  kou: [
    { pinyin: "kōu", char: "抠" },
    { pinyin: "kǒu", char: "口" },
    { pinyin: "kòu", char: "扣" },
  ],
  ku: [
    { pinyin: "kū", char: "哭" },
    { pinyin: "kǔ", char: "苦" },
    { pinyin: "kù", char: "酷" },
  ],
  kua: [
    { pinyin: "kuā", char: "夸" },
    { pinyin: "kuǎ", char: "垮" },
    { pinyin: "kuà", char: "跨" },
  ],
  kuai: [{ pinyin: "kuài", char: "快" }],
  kuan: [
    { pinyin: "kuān", char: "宽" },
    { pinyin: "kuǎn", char: "款" },
  ],
  kuang: [
    { pinyin: "kuāng", char: "筐" },
    { pinyin: "kuáng", char: "狂" },
    { pinyin: "kuàng", char: "况" },
  ],
  kui: [
    { pinyin: "kuī", char: "亏" },
    { pinyin: "kuí", char: "魁" },
    { pinyin: "kuì", char: "溃" },
  ],
  kun: [
    { pinyin: "kūn", char: "坤" },
    { pinyin: "kǔn", char: "捆" },
    { pinyin: "kùn", char: "困" },
  ],
  kuo: [{ pinyin: "kuò", char: "阔" }],
  la: [
    { pinyin: "lā", char: "拉" },
    { pinyin: "lá", char: "旯" },
    { pinyin: "lǎ", char: "喇" },
    { pinyin: "là", char: "辣" },
    { pinyin: "la", char: "啦" },
  ],
  lai: [
    { pinyin: "lái", char: "来" },
    { pinyin: "lài", char: "赖" },
  ],
  lan: [
    { pinyin: "lán", char: "蓝" },
    { pinyin: "lǎn", char: "览" },
    { pinyin: "làn", char: "烂" },
  ],
  lang: [
    { pinyin: "láng", char: "狼" },
    { pinyin: "lǎng", char: "朗" },
    { pinyin: "làng", char: "浪" },
  ],
  lao: [
    { pinyin: "lāo", char: "捞" },
    { pinyin: "láo", char: "劳" },
    { pinyin: "lǎo", char: "老" },
    { pinyin: "lào", char: "烙" },
  ],
  le: [
    { pinyin: "lè", char: "乐" },
    { pinyin: "le", char: "了" },
  ],
  lei: [
    { pinyin: "lēi", char: "勒" },
    { pinyin: "léi", char: "雷" },
    { pinyin: "lěi", char: "垒" },
    { pinyin: "lèi", char: "类" },
  ],
  leng: [
    { pinyin: "léng", char: "棱" },
    { pinyin: "lěng", char: "冷" },
    { pinyin: "lèng", char: "愣" },
  ],
  li: [
    { pinyin: "lī", char: "哩" },
    { pinyin: "lí", char: "离" },
    { pinyin: "lǐ", char: "里" },
    { pinyin: "lì", char: "力" },
    { pinyin: "li", char: "哩" },
  ],
  lia: [{ pinyin: "liǎ", char: "俩" }],
  lian: [
    { pinyin: "lián", char: "连" },
    { pinyin: "liǎn", char: "脸" },
    { pinyin: "liàn", char: "练" },
  ],
  liang: [
    { pinyin: "liáng", char: "良" },
    { pinyin: "liǎng", char: "两" },
    { pinyin: "liàng", char: "辆" },
  ],
  liao: [
    { pinyin: "liāo", char: "撩" },
    { pinyin: "liáo", char: "聊" },
    { pinyin: "liǎo", char: "了" },
    { pinyin: "liào", char: "料" },
  ],
  lie: [
    { pinyin: "liē", char: "咧" },
    { pinyin: "liè", char: "裂" },
  ],
  lin: [
    { pinyin: "lín", char: "林" },
    { pinyin: "lǐn", char: "凛" },
    { pinyin: "lìn", char: "吝" },
  ],
  ling: [
    { pinyin: "líng", char: "灵" },
    { pinyin: "lǐng", char: "领" },
    { pinyin: "lìng", char: "另" },
  ],
  liu: [
    { pinyin: "liū", char: "溜" },
    { pinyin: "liú", char: "流" },
    { pinyin: "liǔ", char: "柳" },
    { pinyin: "liù", char: "六" },
  ],
  long: [
    { pinyin: "lóng", char: "龙" },
    { pinyin: "lǒng", char: "拢" },
  ],
  lou: [
    { pinyin: "lóu", char: "楼" },
    { pinyin: "lǒu", char: "搂" },
    { pinyin: "lòu", char: "漏" },
  ],
  lu: [
    { pinyin: "lū", char: "噜" },
    { pinyin: "lú", char: "炉" },
    { pinyin: "lǔ", char: "鲁" },
    { pinyin: "lù", char: "路" },
  ],
  luan: [
    { pinyin: "luán", char: "峦" },
    { pinyin: "luǎn", char: "卵" },
    { pinyin: "luàn", char: "乱" },
  ],
  lun: [
    { pinyin: "lún", char: "轮" },
    { pinyin: "lùn", char: "论" },
  ],
  luo: [
    { pinyin: "luō", char: "啰" },
    { pinyin: "luó", char: "罗" },
    { pinyin: "luǒ", char: "裸" },
    { pinyin: "luò", char: "落" },
    { pinyin: "luo", char: "咯" },
  ],
  lv: [
    { pinyin: "lǘ", char: "驴" },
    { pinyin: "lǚ", char: "旅" },
    { pinyin: "lǜ", char: "绿" },
  ],
  lve: [{ pinyin: "lüè", char: "略" }],
  m: [{ pinyin: "m", char: "呒" }],
  ma: [
    { pinyin: "mā", char: "妈" },
    { pinyin: "má", char: "麻" },
    { pinyin: "mǎ", char: "马" },
    { pinyin: "mà", char: "骂" },
    { pinyin: "ma", char: "吗" },
  ],
  mai: [
    { pinyin: "mái", char: "埋" },
    { pinyin: "mǎi", char: "买" },
    { pinyin: "mài", char: "卖" },
  ],
  man: [
    { pinyin: "mán", char: "蛮" },
    { pinyin: "mǎn", char: "满" },
    { pinyin: "màn", char: "慢" },
  ],
  mang: [
    { pinyin: "máng", char: "忙" },
    { pinyin: "mǎng", char: "莽" },
  ],
  mao: [
    { pinyin: "māo", char: "猫" },
    { pinyin: "máo", char: "毛" },
    { pinyin: "mǎo", char: "卯" },
    { pinyin: "mào", char: "冒" },
  ],
  me: [{ pinyin: "me", char: "么" }],
  mei: [
    { pinyin: "méi", char: "没" },
    { pinyin: "měi", char: "美" },
    { pinyin: "mèi", char: "妹" },
  ],
  men: [
    { pinyin: "mén", char: "门" },
    { pinyin: "men", char: "们" },
  ],
  meng: [
    { pinyin: "méng", char: "蒙" },
    { pinyin: "měng", char: "猛" },
    { pinyin: "mèng", char: "梦" },
  ],
  mi: [
    { pinyin: "mī", char: "眯" },
    { pinyin: "mí", char: "迷" },
    { pinyin: "mǐ", char: "米" },
    { pinyin: "mì", char: "密" },
  ],
  mian: [
    { pinyin: "mián", char: "棉" },
    { pinyin: "miǎn", char: "免" },
    { pinyin: "miàn", char: "面" },
  ],
  miao: [
    { pinyin: "miáo", char: "描" },
    { pinyin: "miǎo", char: "秒" },
    { pinyin: "miào", char: "妙" },
  ],
  mie: [
    { pinyin: "miē", char: "咩" },
    { pinyin: "miè", char: "灭" },
  ],
  min: [
    { pinyin: "mín", char: "民" },
    { pinyin: "mǐn", char: "敏" },
  ],
  ming: [
    { pinyin: "míng", char: "名" },
    { pinyin: "mìng", char: "命" },
  ],
  miu: [{ pinyin: "miù", char: "谬" }],
  mo: [
    { pinyin: "mō", char: "摸" },
    { pinyin: "mó", char: "模" },
    { pinyin: "mǒ", char: "抹" },
    { pinyin: "mò", char: "末" },
  ],
  mou: [
    { pinyin: "móu", char: "谋" },
    { pinyin: "mǒu", char: "某" },
  ],
  mu: [
    { pinyin: "mú", char: "模" },
    { pinyin: "mǔ", char: "母" },
    { pinyin: "mù", char: "目" },
  ],
  na: [
    { pinyin: "nā", char: "拿" },
    { pinyin: "ná", char: "哪" },
    { pinyin: "nǎ", char: "哪" },
    { pinyin: "nà", char: "那" },
    { pinyin: "na", char: "那" },
  ],
  nai: [
    { pinyin: "nǎi", char: "乃" },
    { pinyin: "nài", char: "耐" },
  ],
  nan: [
    { pinyin: "nán", char: "男" },
    { pinyin: "nǎn", char: "喃" },
    { pinyin: "nàn", char: "难" },
  ],
  nang: [{ pinyin: "náng", char: "囊" }],
  nao: [
    { pinyin: "náo", char: "挠" },
    { pinyin: "nǎo", char: "脑" },
    { pinyin: "nào", char: "闹" },
  ],
  ne: [{ pinyin: "ne", char: "呢" }],
  nei: [{ pinyin: "nèi", char: "内" }],
  nen: [{ pinyin: "nèn", char: "嫩" }],
  neng: [{ pinyin: "néng", char: "能" }],
  ni: [
    { pinyin: "nī", char: "妮" },
    { pinyin: "ní", char: "泥" },
    { pinyin: "nǐ", char: "你" },
    { pinyin: "nì", char: "逆" },
  ],
  nian: [
    { pinyin: "nián", char: "年" },
    { pinyin: "niǎn", char: "捻" },
    { pinyin: "niàn", char: "念" },
  ],
  niang: [{ pinyin: "niáng", char: "娘" }],
  niao: [
    { pinyin: "niǎo", char: "鸟" },
    { pinyin: "niào", char: "尿" },
  ],
  nie: [
    { pinyin: "niē", char: "捏" },
    { pinyin: "niè", char: "聂" },
  ],
  nin: [{ pinyin: "nín", char: "您" }],
  ning: [
    { pinyin: "níng", char: "宁" },
    { pinyin: "nìng", char: "拧" },
  ],
  niu: [
    { pinyin: "niú", char: "牛" },
    { pinyin: "niǔ", char: "扭" },
    { pinyin: "niù", char: "拗" },
  ],
  nong: [
    { pinyin: "nóng", char: "农" },
    { pinyin: "nòng", char: "弄" },
  ],
  nou: [],
  nu: [
    { pinyin: "nú", char: "奴" },
    { pinyin: "nǔ", char: "努" },
    { pinyin: "nù", char: "怒" },
  ],
  nuan: [{ pinyin: "nuǎn", char: "暖" }],
  nun: [],
  nuo: [
    { pinyin: "nuó", char: "挪" },
    { pinyin: "nuò", char: "诺" },
  ],
  nv: [{ pinyin: "nǚ", char: "女" }],
  nve: [{ pinyin: "nüè", char: "虐" }],
  o: [
    { pinyin: "ó", char: "哦" },
    { pinyin: "ò", char: "哦" },
    { pinyin: "o", char: "哦" },
  ],
  ou: [
    { pinyin: "ōu", char: "欧" },
    { pinyin: "ǒu", char: "偶" },
  ],
  pa: [
    { pinyin: "pā", char: "趴" },
    { pinyin: "pá", char: "爬" },
    { pinyin: "pà", char: "怕" },
  ],
  pai: [
    { pinyin: "pāi", char: "拍" },
    { pinyin: "pái", char: "排" },
    { pinyin: "pài", char: "派" },
  ],
  pan: [
    { pinyin: "pān", char: "潘" },
    { pinyin: "pán", char: "盘" },
    { pinyin: "pàn", char: "盼" },
  ],
  pang: [
    { pinyin: "páng", char: "旁" },
    { pinyin: "pàng", char: "胖" },
  ],
  pao: [
    { pinyin: "pāo", char: "抛" },
    { pinyin: "páo", char: "刨" },
    { pinyin: "pǎo", char: "跑" },
    { pinyin: "pào", char: "炮" },
  ],
  pei: [
    { pinyin: "péi", char: "陪" },
    { pinyin: "pěi", char: "胚" },
    { pinyin: "pèi", char: "配" },
  ],
  pen: [
    { pinyin: "pēn", char: "喷" },
    { pinyin: "pén", char: "盆" },
  ],
  peng: [
    { pinyin: "pēng", char: "烹" },
    { pinyin: "péng", char: "朋" },
    { pinyin: "pěng", char: "捧" },
    { pinyin: "pèng", char: "碰" },
  ],
  pi: [
    { pinyin: "pī", char: "批" },
    { pinyin: "pí", char: "皮" },
    { pinyin: "pǐ", char: "匹" },
    { pinyin: "pì", char: "屁" },
  ],
  pian: [
    { pinyin: "piān", char: "篇" },
    { pinyin: "pián", char: "便" },
    { pinyin: "piàn", char: "片" },
  ],
  piao: [
    { pinyin: "piāo", char: "飘" },
    { pinyin: "piáo", char: "瓢" },
    { pinyin: "piǎo", char: "瞟" },
    { pinyin: "piào", char: "票" },
  ],
  pie: [
    { pinyin: "piē", char: "撇" },
    { pinyin: "piě", char: "瞥" },
  ],
  pin: [
    { pinyin: "pīn", char: "拼" },
    { pinyin: "pín", char: "贫" },
    { pinyin: "pǐn", char: "品" },
  ],
  ping: [
    { pinyin: "píng", char: "平" },
    { pinyin: "pǐng", char: "娉" },
  ],
  po: [
    { pinyin: "pō", char: "坡" },
    { pinyin: "pó", char: "婆" },
    { pinyin: "pǒ", char: "叵" },
    { pinyin: "pò", char: "破" },
  ],
  pou: [
    { pinyin: "pōu", char: "剖" },
    { pinyin: "pǒu", char: "掊" },
  ],
  pu: [
    { pinyin: "pū", char: "扑" },
    { pinyin: "pú", char: "葡" },
    { pinyin: "pǔ", char: "普" },
    { pinyin: "pù", char: "铺" },
  ],
  qi: [
    { pinyin: "qī", char: "七" },
    { pinyin: "qí", char: "其" },
    { pinyin: "qǐ", char: "起" },
    { pinyin: "qì", char: "气" },
  ],
  qia: [
    { pinyin: "qiā", char: "掐" },
    { pinyin: "qiǎ", char: "卡" },
  ],
  qian: [
    { pinyin: "qiān", char: "千" },
    { pinyin: "qián", char: "前" },
    { pinyin: "qiǎn", char: "浅" },
    { pinyin: "qiàn", char: "欠" },
  ],
  qiang: [
    { pinyin: "qiāng", char: "枪" },
    { pinyin: "qiáng", char: "强" },
    { pinyin: "qiǎng", char: "抢" },
    { pinyin: "qiàng", char: "呛" },
  ],
  qiao: [
    { pinyin: "qiāo", char: "敲" },
    { pinyin: "qiáo", char: "桥" },
    { pinyin: "qiǎo", char: "巧" },
    { pinyin: "qiào", char: "俏" },
  ],
  qie: [
    { pinyin: "qiē", char: "切" },
    { pinyin: "qiè", char: "切" },
  ],
  qin: [
    { pinyin: "qīn", char: "亲" },
    { pinyin: "qín", char: "琴" },
    { pinyin: "qǐn", char: "寝" },
  ],
  qing: [
    { pinyin: "qīng", char: "青" },
    { pinyin: "qíng", char: "情" },
    { pinyin: "qǐng", char: "请" },
    { pinyin: "qìng", char: "庆" },
  ],
  qiong: [{ pinyin: "qióng", char: "穷" }],
  qiu: [
    { pinyin: "qiū", char: "秋" },
    { pinyin: "qiú", char: "球" },
  ],
  qu: [
    { pinyin: "qū", char: "区" },
    { pinyin: "qú", char: "渠" },
    { pinyin: "qǔ", char: "取" },
    { pinyin: "qù", char: "去" },
  ],
  quan: [
    { pinyin: "quān", char: "圈" },
    { pinyin: "quán", char: "全" },
    { pinyin: "quàn", char: "劝" },
  ],
  que: [
    { pinyin: "quē", char: "缺" },
    { pinyin: "què", char: "却" },
  ],
  qun: [{ pinyin: "qún", char: "群" }],
  ran: [
    { pinyin: "rán", char: "然" },
    { pinyin: "rǎn", char: "染" },
  ],
  rang: [
    { pinyin: "rāng", char: "嚷" },
    { pinyin: "ráng", char: "瓤" },
    { pinyin: "rǎng", char: "壤" },
    { pinyin: "ràng", char: "让" },
  ],
  rao: [
    { pinyin: "ráo", char: "饶" },
    { pinyin: "rǎo", char: "扰" },
  ],
  re: [
    { pinyin: "rě", char: "惹" },
    { pinyin: "rè", char: "热" },
  ],
  ren: [
    { pinyin: "rén", char: "人" },
    { pinyin: "rěn", char: "忍" },
    { pinyin: "rèn", char: "认" },
  ],
  reng: [
    { pinyin: "rēng", char: "扔" },
    { pinyin: "réng", char: "仍" },
  ],
  ri: [{ pinyin: "rì", char: "日" }],
  rong: [
    { pinyin: "róng", char: "容" },
    { pinyin: "rǒng", char: "冗" },
  ],
  rou: [
    { pinyin: "róu", char: "柔" },
    { pinyin: "ròu", char: "肉" },
  ],
  ru: [
    { pinyin: "rú", char: "如" },
    { pinyin: "rǔ", char: "乳" },
    { pinyin: "rù", char: "入" },
  ],
  ruan: [{ pinyin: "ruǎn", char: "软" }],
  rui: [
    { pinyin: "ruí", char: "蕤" },
    { pinyin: "ruǐ", char: "蕊" },
    { pinyin: "ruì", char: "瑞" },
  ],
  run: [{ pinyin: "rùn", char: "润" }],
  ruo: [{ pinyin: "ruò", char: "若" }],
  sa: [
    { pinyin: "sā", char: "撒" },
    { pinyin: "sǎ", char: "洒" },
    { pinyin: "sà", char: "萨" },
  ],
  sai: [
    { pinyin: "sāi", char: "腮" },
    { pinyin: "sài", char: "赛" },
  ],
  san: [
    { pinyin: "sān", char: "三" },
    { pinyin: "sǎn", char: "伞" },
    { pinyin: "sàn", char: "散" },
  ],
  sang: [
    { pinyin: "sāng", char: "桑" },
    { pinyin: "sǎng", char: "嗓" },
    { pinyin: "sàng", char: "丧" },
  ],
  sao: [
    { pinyin: "sāo", char: "骚" },
    { pinyin: "sǎo", char: "扫" },
    { pinyin: "sào", char: "嫂" },
  ],
  se: [{ pinyin: "sè", char: "色" }],
  sen: [{ pinyin: "sēn", char: "森" }],
  seng: [{ pinyin: "sēng", char: "僧" }],
  sha: [
    { pinyin: "shā", char: "杀" },
    { pinyin: "shá", char: "啥" },
    { pinyin: "shǎ", char: "傻" },
    { pinyin: "shà", char: "厦" },
  ],
  shai: [
    { pinyin: "shǎi", char: "色" },
    { pinyin: "shài", char: "晒" },
  ],
  shan: [
    { pinyin: "shān", char: "山" },
    { pinyin: "shǎn", char: "闪" },
    { pinyin: "shàn", char: "善" },
  ],
  shang: [
    { pinyin: "shāng", char: "商" },
    { pinyin: "shǎng", char: "赏" },
    { pinyin: "shàng", char: "上" },
  ],
  shao: [
    { pinyin: "shāo", char: "烧" },
    { pinyin: "sháo", char: "勺" },
    { pinyin: "shǎo", char: "少" },
    { pinyin: "shào", char: "绍" },
  ],
  she: [
    { pinyin: "shē", char: "奢" },
    { pinyin: "shé", char: "蛇" },
    { pinyin: "shě", char: "舍" },
    { pinyin: "shè", char: "社" },
  ],
  shei: [{ pinyin: "shéi", char: "谁" }],
  shen: [
    { pinyin: "shēn", char: "深" },
    { pinyin: "shén", char: "神" },
    { pinyin: "shěn", char: "审" },
    { pinyin: "shèn", char: "甚" },
  ],
  sheng: [
    { pinyin: "shēng", char: "生" },
    { pinyin: "shéng", char: "绳" },
    { pinyin: "shěng", char: "省" },
    { pinyin: "shèng", char: "剩" },
  ],
  shi: [
    { pinyin: "shī", char: "师" },
    { pinyin: "shí", char: "十" },
    { pinyin: "shǐ", char: "使" },
    { pinyin: "shì", char: "是" },
  ],
  shou: [
    { pinyin: "shōu", char: "收" },
    { pinyin: "shǒu", char: "手" },
    { pinyin: "shòu", char: "受" },
  ],
  shu: [
    { pinyin: "shū", char: "书" },
    { pinyin: "shú", char: "熟" },
    { pinyin: "shǔ", char: "属" },
    { pinyin: "shù", char: "树" },
  ],
  shua: [
    { pinyin: "shuā", char: "刷" },
    { pinyin: "shuǎ", char: "耍" },
    { pinyin: "shuà", char: "唰" },
  ],
  shuai: [
    { pinyin: "shuāi", char: "摔" },
    { pinyin: "shuǎi", char: "甩" },
    { pinyin: "shuài", char: "帅" },
  ],
  shuan: [
    { pinyin: "shuān", char: "栓" },
    { pinyin: "shuàn", char: "涮" },
  ],
  shuang: [{ pinyin: "shuāng", char: "双" }],
  shui: [
    { pinyin: "shuí", char: "谁" },
    { pinyin: "shuǐ", char: "水" },
  ],
  shun: [
    { pinyin: "shǔn", char: "吮" },
    { pinyin: "shùn", char: "顺" },
  ],
  shuo: [
    { pinyin: "shuō", char: "说" },
    { pinyin: "shuò", char: "硕" },
  ],
  si: [
    { pinyin: "sī", char: "思" },
    { pinyin: "sǐ", char: "死" },
    { pinyin: "sì", char: "四" },
  ],
  song: [
    { pinyin: "sōng", char: "松" },
    { pinyin: "sǒng", char: "耸" },
    { pinyin: "sòng", char: "送" },
  ],
  sou: [
    { pinyin: "sōu", char: "搜" },
    { pinyin: "sǒu", char: "叟" },
  ],
  su: [
    { pinyin: "sū", char: "苏" },
    { pinyin: "sú", char: "俗" },
    { pinyin: "sù", char: "速" },
  ],
  suan: [
    { pinyin: "suān", char: "酸" },
    { pinyin: "suàn", char: "算" },
  ],
  sui: [
    { pinyin: "suī", char: "虽" },
    { pinyin: "suí", char: "随" },
    { pinyin: "suǐ", char: "髓" },
    { pinyin: "suì", char: "岁" },
  ],
  sun: [
    { pinyin: "sūn", char: "孙" },
    { pinyin: "sǔn", char: "损" },
  ],
  suo: [
    { pinyin: "suō", char: "缩" },
    { pinyin: "suǒ", char: "所" },
  ],
  ta: [
    { pinyin: "tā", char: "他" },
    { pinyin: "tǎ", char: "塔" },
    { pinyin: "tà", char: "踏" },
  ],
  tai: [
    { pinyin: "tāi", char: "胎" },
    { pinyin: "tài", char: "太" },
  ],
  tan: [
    { pinyin: "tān", char: "贪" },
    { pinyin: "tán", char: "谈" },
    { pinyin: "tǎn", char: "坦" },
    { pinyin: "tàn", char: "探" },
  ],
  tang: [
    { pinyin: "tāng", char: "汤" },
    { pinyin: "táng", char: "唐" },
    { pinyin: "tǎng", char: "躺" },
    { pinyin: "tàng", char: "烫" },
  ],
  tao: [
    { pinyin: "tāo", char: "掏" },
    { pinyin: "táo", char: "桃" },
    { pinyin: "tǎo", char: "讨" },
    { pinyin: "tào", char: "套" },
  ],
  te: [{ pinyin: "tè", char: "特" }],
  teng: [{ pinyin: "téng", char: "疼" }],
  ti: [
    { pinyin: "tī", char: "梯" },
    { pinyin: "tí", char: "提" },
    { pinyin: "tǐ", char: "体" },
    { pinyin: "tì", char: "替" },
  ],
  tian: [
    { pinyin: "tiān", char: "天" },
    { pinyin: "tián", char: "田" },
    { pinyin: "tiǎn", char: "舔" },
  ],
  tiao: [
    { pinyin: "tiāo", char: "挑" },
    { pinyin: "tiáo", char: "条" },
    { pinyin: "tiǎo", char: "窕" },
  ],
  tie: [
    { pinyin: "tiē", char: "贴" },
    { pinyin: "tiě", char: "铁" },
    { pinyin: "tiè", char: "帖" },
  ],
  ting: [
    { pinyin: "tīng", char: "听" },
    { pinyin: "tíng", char: "停" },
    { pinyin: "tǐng", char: "挺" },
  ],
  tong: [
    { pinyin: "tōng", char: "通" },
    { pinyin: "tóng", char: "同" },
    { pinyin: "tǒng", char: "桶" },
    { pinyin: "tòng", char: "痛" },
  ],
  tou: [
    { pinyin: "tōu", char: "偷" },
    { pinyin: "tóu", char: "头" },
    { pinyin: "tòu", char: "透" },
  ],
  tu: [
    { pinyin: "tū", char: "秃" },
    { pinyin: "tú", char: "图" },
    { pinyin: "tǔ", char: "土" },
    { pinyin: "tù", char: "兔" },
  ],
  tuan: [{ pinyin: "tuán", char: "团" }],
  tui: [
    { pinyin: "tuī", char: "推" },
    { pinyin: "tuí", char: "颓" },
    { pinyin: "tuì", char: "退" },
  ],
  tun: [
    { pinyin: "tūn", char: "吞" },
    { pinyin: "tún", char: "屯" },
  ],
  tuo: [
    { pinyin: "tuō", char: "拖" },
    { pinyin: "tuó", char: "驼" },
    { pinyin: "tuǒ", char: "妥" },
    { pinyin: "tuò", char: "唾" },
  ],
  wa: [
    { pinyin: "wā", char: "挖" },
    { pinyin: "wá", char: "娃" },
    { pinyin: "wǎ", char: "瓦" },
    { pinyin: "wà", char: "袜" },
  ],
  wai: [
    { pinyin: "wāi", char: "歪" },
    { pinyin: "wài", char: "外" },
  ],
  wan: [
    { pinyin: "wān", char: "弯" },
    { pinyin: "wán", char: "完" },
    { pinyin: "wǎn", char: "晚" },
    { pinyin: "wàn", char: "万" },
  ],
  wang: [
    { pinyin: "wāng", char: "汪" },
    { pinyin: "wáng", char: "王" },
    { pinyin: "wǎng", char: "往" },
    { pinyin: "wàng", char: "忘" },
  ],
  wei: [
    { pinyin: "wēi", char: "威" },
    { pinyin: "wéi", char: "为" },
    { pinyin: "wěi", char: "尾" },
    { pinyin: "wèi", char: "位" },
  ],
  wen: [
    { pinyin: "wēn", char: "温" },
    { pinyin: "wén", char: "文" },
    { pinyin: "wěn", char: "稳" },
    { pinyin: "wèn", char: "问" },
  ],
  weng: [
    { pinyin: "wēng", char: "翁" },
    { pinyin: "wěng", char: "蓊" },
  ],
  wo: [
    { pinyin: "wō", char: "窝" },
    { pinyin: "wǒ", char: "我" },
    { pinyin: "wò", char: "卧" },
  ],
  wu: [
    { pinyin: "wū", char: "乌" },
    { pinyin: "wú", char: "无" },
    { pinyin: "wǔ", char: "五" },
    { pinyin: "wù", char: "物" },
  ],
  xi: [
    { pinyin: "xī", char: "西" },
    { pinyin: "xí", char: "习" },
    { pinyin: "xǐ", char: "洗" },
    { pinyin: "xì", char: "戏" },
  ],
  xia: [
    { pinyin: "xiā", char: "虾" },
    { pinyin: "xiá", char: "峡" },
    { pinyin: "xià", char: "下" },
  ],
  xian: [
    { pinyin: "xiān", char: "先" },
    { pinyin: "xián", char: "嫌" },
    { pinyin: "xiǎn", char: "显" },
    { pinyin: "xiàn", char: "现" },
  ],
  xiang: [
    { pinyin: "xiāng", char: "香" },
    { pinyin: "xiáng", char: "祥" },
    { pinyin: "xiǎng", char: "想" },
    { pinyin: "xiàng", char: "向" },
  ],
  xiao: [
    { pinyin: "xiāo", char: "消" },
    { pinyin: "xiáo", char: "淆" },
    { pinyin: "xiǎo", char: "小" },
    { pinyin: "xiào", char: "笑" },
  ],
  xie: [
    { pinyin: "xiē", char: "些" },
    { pinyin: "xié", char: "斜" },
    { pinyin: "xiě", char: "写" },
    { pinyin: "xiè", char: "谢" },
  ],
  xin: [
    { pinyin: "xīn", char: "新" },
    { pinyin: "xìn", char: "信" },
  ],
  xing: [
    { pinyin: "xīng", char: "星" },
    { pinyin: "xíng", char: "行" },
    { pinyin: "xǐng", char: "醒" },
    { pinyin: "xìng", char: "性" },
  ],
  xiong: [
    { pinyin: "xiōng", char: "兄" },
    { pinyin: "xióng", char: "熊" },
  ],
  xiu: [
    { pinyin: "xiū", char: "休" },
    { pinyin: "xiǔ", char: "朽" },
    { pinyin: "xiù", char: "秀" },
  ],
  xu: [
    { pinyin: "xū", char: "须" },
    { pinyin: "xú", char: "徐" },
    { pinyin: "xǔ", char: "许" },
    { pinyin: "xù", char: "序" },
  ],
  xuan: [
    { pinyin: "xuān", char: "宣" },
    { pinyin: "xuán", char: "悬" },
    { pinyin: "xuǎn", char: "选" },
    { pinyin: "xuàn", char: "炫" },
  ],
  xue: [
    { pinyin: "xuē", char: "薛" },
    { pinyin: "xué", char: "学" },
    { pinyin: "xuě", char: "雪" },
  ],
  xun: [
    { pinyin: "xūn", char: "熏" },
    { pinyin: "xún", char: "寻" },
    { pinyin: "xùn", char: "讯" },
  ],
  ya: [
    { pinyin: "yā", char: "压" },
    { pinyin: "yá", char: "牙" },
    { pinyin: "yǎ", char: "雅" },
    { pinyin: "yà", char: "亚" },
  ],
  yan: [
    { pinyin: "yān", char: "烟" },
    { pinyin: "yán", char: "言" },
    { pinyin: "yǎn", char: "眼" },
    { pinyin: "yàn", char: "燕" },
  ],
  yang: [
    { pinyin: "yāng", char: "央" },
    { pinyin: "yáng", char: "羊" },
    { pinyin: "yǎng", char: "养" },
    { pinyin: "yàng", char: "样" },
  ],
  yao: [
    { pinyin: "yāo", char: "腰" },
    { pinyin: "yáo", char: "摇" },
    { pinyin: "yǎo", char: "咬" },
    { pinyin: "yào", char: "要" },
  ],
  ye: [
    { pinyin: "yē", char: "椰" },
    { pinyin: "yé", char: "爷" },
    { pinyin: "yě", char: "也" },
    { pinyin: "yè", char: "夜" },
  ],
  yi: [
    { pinyin: "yī", char: "一" },
    { pinyin: "yí", char: "移" },
    { pinyin: "yǐ", char: "以" },
    { pinyin: "yì", char: "意" },
  ],
  yin: [
    { pinyin: "yīn", char: "因" },
    { pinyin: "yín", char: "银" },
    { pinyin: "yǐn", char: "引" },
    { pinyin: "yìn", char: "印" },
  ],
  ying: [
    { pinyin: "yīng", char: "英" },
    { pinyin: "yíng", char: "迎" },
    { pinyin: "yǐng", char: "影" },
    { pinyin: "yìng", char: "硬" },
  ],
  yo: [{ pinyin: "yo", char: "哟" }],
  yong: [
    { pinyin: "yōng", char: "拥" },
    { pinyin: "yǒng", char: "永" },
    { pinyin: "yòng", char: "用" },
  ],
  you: [
    { pinyin: "yōu", char: "优" },
    { pinyin: "yóu", char: "由" },
    { pinyin: "yǒu", char: "有" },
    { pinyin: "yòu", char: "又" },
  ],
  yu: [
    { pinyin: "yū", char: "迂" },
    { pinyin: "yú", char: "鱼" },
    { pinyin: "yǔ", char: "雨" },
    { pinyin: "yù", char: "玉" },
  ],
  yuan: [
    { pinyin: "yuān", char: "冤" },
    { pinyin: "yuán", char: "元" },
    { pinyin: "yuǎn", char: "远" },
    { pinyin: "yuàn", char: "院" },
  ],
  yue: [
    { pinyin: "yuē", char: "约" },
    { pinyin: "yuè", char: "月" },
  ],
  yun: [
    { pinyin: "yūn", char: "晕" },
    { pinyin: "yún", char: "云" },
    { pinyin: "yǔn", char: "允" },
    { pinyin: "yùn", char: "运" },
  ],
  za: [
    { pinyin: "zā", char: "匝" },
    { pinyin: "zá", char: "杂" },
    { pinyin: "zǎ", char: "咋" },
  ],
  zai: [
    { pinyin: "zāi", char: "灾" },
    { pinyin: "zǎi", char: "宰" },
    { pinyin: "zài", char: "在" },
  ],
  zan: [
    { pinyin: "zān", char: "簪" },
    { pinyin: "zǎn", char: "攒" },
    { pinyin: "zàn", char: "赞" },
  ],
  zang: [
    { pinyin: "zāng", char: "脏" },
    { pinyin: "zàng", char: "藏" },
  ],
  zao: [
    { pinyin: "zāo", char: "遭" },
    { pinyin: "záo", char: "凿" },
    { pinyin: "zǎo", char: "早" },
    { pinyin: "zào", char: "造" },
  ],
  ze: [
    { pinyin: "zé", char: "则" },
    { pinyin: "zéi", char: "贼" },
    { pinyin: "zè", char: "仄" },
  ],
  zei: [{ pinyin: "zéi", char: "贼" }],
  zen: [{ pinyin: "zěn", char: "怎" }],
  zeng: [
    { pinyin: "zēng", char: "增" },
    { pinyin: "zèng", char: "赠" },
  ],
  zha: [
    { pinyin: "zhā", char: "扎" },
    { pinyin: "zhá", char: "扎" },
    { pinyin: "zhǎ", char: "眨" },
    { pinyin: "zhà", char: "炸" },
  ],
  zhai: [
    { pinyin: "zhāi", char: "摘" },
    { pinyin: "zhái", char: "宅" },
    { pinyin: "zhǎi", char: "窄" },
    { pinyin: "zhài", char: "债" },
  ],
  zhan: [
    { pinyin: "zhān", char: "沾" },
    { pinyin: "zhǎn", char: "展" },
    { pinyin: "zhàn", char: "站" },
  ],
  zhang: [
    { pinyin: "zhāng", char: "张" },
    { pinyin: "zhǎng", char: "长" },
    { pinyin: "zhàng", char: "丈" },
  ],
  zhao: [
    { pinyin: "zhāo", char: "招" },
    { pinyin: "zhǎo", char: "找" },
    { pinyin: "zhào", char: "照" },
  ],
  zhe: [
    { pinyin: "zhē", char: "遮" },
    { pinyin: "zhé", char: "折" },
    { pinyin: "zhě", char: "者" },
    { pinyin: "zhè", char: "这" },
    { pinyin: "zhe", char: "着" },
  ],
  zhen: [
    { pinyin: "zhēn", char: "真" },
    { pinyin: "zhěn", char: "枕" },
    { pinyin: "zhèn", char: "阵" },
  ],
  zheng: [
    { pinyin: "zhēng", char: "争" },
    { pinyin: "zhěng", char: "整" },
    { pinyin: "zhèng", char: "正" },
  ],
  zhi: [
    { pinyin: "zhī", char: "之" },
    { pinyin: "zhí", char: "直" },
    { pinyin: "zhǐ", char: "只" },
    { pinyin: "zhì", char: "至" },
  ],
  zhong: [
    { pinyin: "zhōng", char: "中" },
    { pinyin: "zhǒng", char: "种" },
    { pinyin: "zhòng", char: "重" },
  ],
  zhou: [
    { pinyin: "zhōu", char: "周" },
    { pinyin: "zhóu", char: "轴" },
    { pinyin: "zhǒu", char: "肘" },
    { pinyin: "zhòu", char: "皱" },
  ],
  zhu: [
    { pinyin: "zhū", char: "朱" },
    { pinyin: "zhú", char: "竹" },
    { pinyin: "zhǔ", char: "主" },
    { pinyin: "zhù", char: "住" },
  ],
  zhua: [{ pinyin: "zhuā", char: "抓" }],
  zhuai: [{ pinyin: "zhuǎi", char: "拽" }],
  zhuan: [
    { pinyin: "zhuān", char: "专" },
    { pinyin: "zhuǎn", char: "转" },
    { pinyin: "zhuàn", char: "赚" },
  ],
  zhuang: [
    { pinyin: "zhuāng", char: "庄" },
    { pinyin: "zhuàng", char: "状" },
  ],
  zhui: [
    { pinyin: "zhuī", char: "追" },
    { pinyin: "zhuì", char: "坠" },
  ],
  zhun: [{ pinyin: "zhǔn", char: "准" }],
  zhuo: [
    { pinyin: "zhuō", char: "桌" },
    { pinyin: "zhuó", char: "着" },
  ],
  zi: [
    { pinyin: "zī", char: "资" },
    { pinyin: "zǐ", char: "子" },
    { pinyin: "zì", char: "字" },
  ],
  zong: [
    { pinyin: "zōng", char: "宗" },
    { pinyin: "zǒng", char: "总" },
    { pinyin: "zòng", char: "纵" },
  ],
  zou: [
    { pinyin: "zǒu", char: "走" },
    { pinyin: "zòu", char: "凑" },
  ],
  zu: [
    { pinyin: "zū", char: "租" },
    { pinyin: "zú", char: "足" },
    { pinyin: "zǔ", char: "组" },
  ],
  zuan: [
    { pinyin: "zuān", char: "钻" },
    { pinyin: "zuǎn", char: "纂" },
  ],
  zui: [
    { pinyin: "zuǐ", char: "嘴" },
    { pinyin: "zuì", char: "最" },
  ],
  zun: [{ pinyin: "zūn", char: "尊" }],
  zuo: [
    { pinyin: "zuō", char: "作" },
    { pinyin: "zuó", char: "昨" },
    { pinyin: "zuǒ", char: "左" },
    { pinyin: "zuò", char: "做" },
  ],
};
